#!/bin/bash
#
# tics2overlay.sh - Convert TI TICS Pro hex register export to a Zephyr DTS
#                   overlay for the LMK03328 driver.
#
# Usage: ./tics2overlay.sh [OPTIONS] <HexRegisterValues.txt>

set -e

usage() {
    cat >&2 <<EOF
Usage: $(basename "$0") [OPTIONS] <HexRegisterValues.txt>

Convert a TI TICS Pro hex register export to a Zephyr DTS overlay for the
LMK03328 driver (compatible = "ti,lmk03328").

Options:
  -b, --bus  <label>   I2C bus node label (default: i2c1)
  -a, --addr <hex>     I2C device address  (default: 54)
  -n, --name <name>    DT node label/name  (default: lmk03328)
  -r, --reset          Add software-reset property
  -o, --output <file>  Write output to file instead of stdout
  -h, --help           Show this help

Example:
  $(basename "$0") -b i2c2 -a 54 -r -o lmk03328.overlay PS33.33-SZG64.8-HexRegisterValues.txt
EOF
}

BUS="i2c1"
ADDR="54"
NAME="lmk03328"
RESET=0
OUTPUT=""
INPUT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -b|--bus)    BUS="$2";    shift 2 ;;
        -a|--addr)   ADDR="$2";   shift 2 ;;
        -n|--name)   NAME="$2";   shift 2 ;;
        -r|--reset)  RESET=1;     shift   ;;
        -o|--output) OUTPUT="$2"; shift 2 ;;
        -h|--help)   usage; exit 0 ;;
        -*)  echo "Error: unknown option: $1" >&2; usage; exit 1 ;;
        *)   INPUT="$1"; shift ;;
    esac
done

if [[ -z "$INPUT" ]]; then
    echo "Error: input file required." >&2; usage; exit 1
fi
if [[ ! -f "$INPUT" ]]; then
    echo "Error: file not found: $INPUT" >&2; exit 1
fi

# Strip leading 0x from address if provided that way
ADDR="${ADDR#0x}"; ADDR="${ADDR#0X}"

# ------------------------------------------------------------------ #
generate() {
    local src
    src="$(basename "$INPUT")"

    cat <<EOF
/*
 * Auto-generated by tics2overlay.sh
 * Source : ${src}
 * Date   : $(date '+%Y-%m-%d %H:%M:%S')
 *
 * Do not edit manually — regenerate from TICS Pro export.
 */

&${BUS} {
	${NAME}: ${NAME}@${ADDR} {
		compatible = "ti,lmk03328";
		reg = <0x${ADDR}>;
		status = "okay";
EOF

    [[ $RESET -eq 1 ]] && echo "		software-reset;"

    echo "		reg-values = <"

    local count=0
    while IFS=$'\t' read -r reg_name hex_val || [[ -n "$reg_name" ]]; do
        # Skip blank lines and anything that isn't a register entry
        [[ -z "$reg_name" ]]    && continue
        [[ "$reg_name" != R* ]] && continue

        # Normalise: strip 0x prefix, strip Windows CR, uppercase, zero-pad to 4
        hex_val="${hex_val#0x}"; hex_val="${hex_val#0X}"
        hex_val="${hex_val%$'\r'}"
        hex_val=$(printf '%04X' "$((16#${hex_val}))")

        local addr="${hex_val:0:2}"
        local val="${hex_val:2:2}"

        printf "\t\t\t0x%s  /* %-5s  addr=0x%s  val=0x%s */\n" \
            "$hex_val" "$reg_name" "$addr" "$val"
        (( count++ )) || true
    done < "$INPUT"

    cat <<EOF
		>;  /* ${count} registers */
	};
};
EOF
}
# ------------------------------------------------------------------ #

if [[ -n "$OUTPUT" ]]; then
    generate > "$OUTPUT"
    echo "Wrote ${OUTPUT}" >&2
else
    generate
fi
